
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[233] =
    {   0,
        0,    0,    0,    0,    0,    0,   59,   57,   55,   56,
       56,   41,   47,   57,   50,   51,   38,   37,   52,   57,
       39,   27,   27,   54,   53,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   57,   44,   44,
       44,   42,   46,   49,   48,   49,    0,    0,   40,   30,
       30,    0,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    0,    0,   30,   27,   27,    0,   24,   24,   24,
       24,   24,   20,   24,   24,   24,   24,   16,   24,   24,
       24,   24,   24,   24,   24,    0,   45,   44,   43,   44,
       48,   31,    0,   30,   30,   30,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   28,   28,   28,
       28,    0,   26,   28,    0,   25,    0,   30,   30,   30,
       27,   27,    0,   24,   24,   24,   24,   24,    3,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
        0,   24,   30,   30,    0,   36,    0,    0,   33,    0,
       28,   28,   28,   29,    0,   26,   25,   30,   30,    0,
       30,   30,   30,    0,   30,   30,   13,   24,   24,   10,
       18,   24,   24,   24,   24,   12,   24,   24,   14,    5,
       24,   24,   22,   24,   17,   24,    0,   34,    0,   35,
        0,   29,    0,   30,   30,   24,   24,   21,   19,   24,

       24,   24,   24,   24,   24,   24,   15,    0,   32,   24,
       24,    9,   24,   24,   24,    8,   23,   24,   24,   24,
       24,    4,    6,   24,   24,   11,    1,   24,    7,   24,
        2,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    8,    6,    6,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,   21,    6,    6,
       22,    6,    6,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   32,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   32,   32,   32,
        6,   44,    6,    6,   45,    6,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   32,   32,   55,   32,   56,
       57,   58,   59,   60,   61,   62,   63,   42,   64,   32,
       32,   32,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    2,    3,    2,
        2,    2,    2,    2,    2,    4,    2,    5,    5,    5,
        2,    2,    6,    7,    6,    6,    6,    7,    8,    8,
        8,    8,    8,    9,    8,    8,    8,    9,    8,    9,
        8,    9,    8,    2,   10,    6,    7,    6,    6,    6,
        7,    8,    8,    8,    8,    9,    8,    8,    8,    9,
        8,    9,    8,    8
    } ;

static const flex_int16_t yy_base[245] =
    {   0,
        0,    0,   62,   64,   69,   71,  511,  599,  599,  599,
      599,  599,  599,  464,  599,  599,  493,  599,  599,   91,
      599,   54,   67,  599,  599,    0,   70,   56,   43,   40,
       55,   94,   94,   65,   92,   91,   92,    0,  599,  599,
      501,  599,   85,  599,  599,  484,  418,  399,  599,  599,
      138,  104,  102,  113,  122,  136,  139,  130,  131,   77,
      148,  159,  161,  174,  181,  189,  198,    0,  140,  160,
      169,  170,    0,  173,  189,  185,  180,    0,  181,  193,
      204,  189,  202,  201,  199,  334,  599,  599,  599,  371,
      599,  599,  352,  217,  236,  245,  221,  342,  207,  316,

      284,  269,  264,  258,  217,  245,  218,  116,  249,  152,
        0,  253,  257,    0,  232,  217,  258,  264,  269,  274,
      279,  289,  302,  257,  263,  263,  287,  284,  300,  288,
      289,  300,  297,  304,  300,  299,  305,  304,  309,  304,
      186,    0,  328,  336,  207,  599,  306,  171,  599,  325,
      350,    0,  352,  354,  358,  362,  169,  364,  367,  377,
      380,  383,  386,  393,  400,  404,    0,  370,  384,    0,
        0,  386,  397,  399,  388,    0,  400,  407,    0,    0,
      396,  397,    0,  401,    0,  410,  137,  599,  412,  599,
      124,  370,  422,  426,  445,  422,  417,    0,    0,  434,

      430,  439,  444,  442,  437,  433,    0,   88,  599,  435,
      436,    0,  443,  441,  447,    0,    0,  441,  442,  456,
      451,    0,    0,  455,  450,    0,    0,  460,    0,  471,
        0,  599,  521,  531,  540,  546,  550,  559,  567,  572,
      576,  579,  586,  589
    } ;

static const flex_int16_t yy_def[245] =
    {   0,
      232,    1,  233,  233,  234,  234,  232,  232,  232,  232,
      232,  232,  232,  235,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  237,  232,  232,
      232,  232,  238,  232,  232,  232,  232,  239,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  240,
      232,  241,  232,  232,  232,  232,  232,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  242,  232,  232,  232,  232,
      232,  232,  239,  232,  232,  232,  232,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  240,  240,  109,
      240,  232,  232,  240,  241,  243,  232,  232,  232,  232,
      232,  232,  232,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      242,  244,  232,  232,  232,  232,  232,  232,  232,  232,
      240,  109,  109,  232,  232,  232,  243,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  244,  232,  232,  232,
      232,  232,  232,  232,  232,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  232,  232,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,    0,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232
    } ;

static const flex_int16_t yy_nxt[664] =
    {   0,
        8,    9,   10,   11,    9,    8,   12,   13,   14,   15,
       16,   17,   18,   19,   18,   20,   21,   22,   23,   23,
       24,   25,   26,   26,   27,   28,   29,   30,   31,   26,
       32,   26,   33,   26,   26,   26,   26,   34,   35,   36,
       26,   26,   37,    8,   38,   26,   26,   27,   28,   29,
       30,   31,   26,   32,   33,   26,   26,   26,   26,   34,
       35,   36,   26,   37,   40,   41,   40,   41,   42,   60,
       42,   45,   46,   45,   46,   74,   75,   61,   72,   63,
       76,   63,   64,   62,   65,   66,   66,   89,   90,   77,
       73,   81,   69,   67,  108,  109,  110,   74,   75,   70,

       61,   72,   76,  209,   71,   43,   62,   43,   50,   51,
       51,   77,   73,   52,   81,   69,   67,   53,   54,   55,
       84,   78,   70,   56,   57,   58,   71,   79,   80,   85,
       59,   82,   83,  151,  151,   99,   52,   97,   98,  209,
       53,   54,   55,   84,   78,   56,   57,   58,  100,   79,
       80,   85,   59,   82,   83,   94,   95,   95,   99,   97,
       98,  101,  102,  112,   96,  104,  113,  106,  107,  153,
      153,  100,  124,  105,  114,  103,  117,  116,  116,  118,
      118,  142,  125,  101,  114,  102,  190,   96,  104,  106,
      107,   50,  119,  119,  124,  105,  120,  103,   65,   65,

       65,   63,  126,   63,   64,  125,  121,  122,  122,  127,
       63,  128,   63,  117,  129,  123,  118,  118,  130,  131,
      132,  133,  188,  137,  126,  138,  134,  139,  135,  140,
      142,  127,  114,  128,   94,   94,   94,  129,  123,  147,
      130,  131,  132,  136,  133,  137,  145,  114,  138,  134,
      139,  135,  140,   94,   95,   95,  148,  143,  150,  143,
      149,  147,   96,  144,  144,  136,  152,  152,  153,  145,
      154,  154,  155,  146,  156,  156,  118,  118,  148,  146,
      150,  158,  159,  159,  146,   96,  161,  162,  162,  167,
      160,   50,  163,  163,  120,  160,  121,  121,  121,  146,

      168,   63,  169,   63,   64,  160,  121,  122,  122,  170,
      171,  167,  175,  160,  164,  123,  164,  117,  160,  165,
      166,  166,  168,  176,  169,  172,  177,  178,  160,  179,
      173,  146,  170,  171,  181,  175,  180,  174,  123,  182,
      183,  184,  185,  186,  189,  176,  144,  144,  172,  177,
      178,  191,  179,  173,  144,  144,  181,  146,  180,  174,
       92,  182,  183,  184,  185,  186,  189,  151,  151,  153,
      153,  154,  154,   89,  191,  192,  192,  155,  142,  156,
      156,  158,  158,  158,  158,  159,  159,  192,  192,  193,
      160,  193,  196,  160,  165,  165,  165,  161,  161,  161,

      161,  162,  162,   94,   94,   94,  160,   92,  117,  160,
      165,  166,  166,  160,  197,  196,  160,  165,  165,  165,
      198,  194,  195,  195,  199,  200,   92,  201,  202,  160,
      160,  203,  160,  204,  205,  206,  207,  197,  208,  165,
      165,  165,  198,  194,  194,  194,  210,  199,  200,  201,
      211,  202,  160,  160,  203,  204,  205,  206,  212,  207,
      213,  208,  194,  195,  195,  214,  215,  216,  225,  210,
      217,  160,  211,  218,  219,  160,  220,  221,  222,  223,
      224,  212,  226,  213,  227,  228,   91,  229,  214,  215,
      216,  225,  217,  230,  160,  218,  219,  231,  220,  221,

      222,  223,  224,   87,   49,  226,  227,   48,  228,  229,
      232,  232,  232,  232,  232,  230,  232,  232,  232,  232,
      231,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       68,   68,   68,   68,   68,   86,   86,   86,   86,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   93,
      232,  232,  232,   93,  232,   93,  111,  111,  111,  115,
      115,  115,  115,  141,  141,  141,  141,  141,  141,  157,
      157,  157,  157,  187,  187,  187,  187,  187,    7,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232
    } ;

static const flex_int16_t yy_chk[664] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    4,    4,    3,   22,
        4,    5,    5,    6,    6,   29,   29,   22,   28,   23,
       30,   23,   23,   22,   23,   23,   23,   43,   43,   31,
       28,   34,   27,   23,   60,   60,   60,   29,   29,   27,

       22,   28,   30,  208,   27,    3,   22,    4,   20,   20,
       20,   31,   28,   20,   34,   27,   23,   20,   20,   20,
       36,   32,   27,   20,   20,   20,   27,   32,   33,   37,
       20,   35,   35,  108,  108,   54,   20,   52,   53,  191,
       20,   20,   20,   36,   32,   20,   20,   20,   55,   32,
       33,   37,   20,   35,   35,   51,   51,   51,   54,   52,
       53,   55,   56,   61,   51,   57,   61,   58,   59,  110,
      110,   55,   69,   57,   62,   56,   63,   62,   62,   63,
       63,  187,   70,   55,  157,   56,  148,   51,   57,   58,
       59,   64,   64,   64,   69,   57,   65,   56,   65,   65,

       65,   66,   71,   66,   66,   70,   66,   66,   66,   72,
       67,   74,   67,   67,   75,   66,   67,   67,   76,   77,
       79,   80,  145,   82,   71,   83,   81,   84,   81,   85,
      141,   72,  116,   74,   94,   94,   94,   75,   66,   99,
       76,   77,   79,   81,   80,   82,   97,  115,   83,   81,
       84,   81,   85,   95,   95,   95,  105,   96,  107,   96,
      106,   99,   95,   96,   96,   81,  109,  109,  109,   97,
      112,  112,  113,  104,  113,  113,  117,  117,  105,  103,
      107,  118,  118,  118,  102,   95,  119,  119,  119,  124,
      118,  120,  120,  120,  121,  119,  121,  121,  121,  101,

      125,  122,  126,  122,  122,  121,  122,  122,  122,  127,
      128,  124,  130,  118,  123,  122,  123,  123,  119,  123,
      123,  123,  125,  131,  126,  129,  132,  133,  121,  134,
      129,  100,  127,  128,  135,  130,  134,  129,  122,  136,
      137,  138,  139,  140,  147,  131,  143,  143,  129,  132,
      133,  150,  134,  129,  144,  144,  135,   98,  134,  129,
       93,  136,  137,  138,  139,  140,  147,  151,  151,  153,
      153,  154,  154,   90,  150,  155,  155,  156,   86,  156,
      156,  158,  158,  158,  159,  159,  159,  192,  192,  160,
      158,  160,  168,  159,  160,  160,  160,  161,  161,  161,

      162,  162,  162,  163,  163,  163,  161,   48,  164,  162,
      164,  164,  164,  158,  169,  168,  159,  165,  165,  165,
      172,  166,  166,  166,  173,  174,   47,  175,  177,  161,
      166,  178,  162,  181,  182,  184,  186,  169,  189,  193,
      193,  193,  172,  194,  194,  194,  196,  173,  174,  175,
      197,  177,  194,  166,  178,  181,  182,  184,  200,  186,
      201,  189,  195,  195,  195,  202,  203,  204,  219,  196,
      205,  195,  197,  206,  210,  194,  211,  213,  214,  215,
      218,  200,  220,  201,  221,  224,   46,  225,  202,  203,
      204,  219,  205,  228,  195,  206,  210,  230,  211,  213,

      214,  215,  218,   41,   17,  220,  221,   14,  224,  225,
        7,    0,    0,    0,    0,  228,    0,    0,    0,    0,
      230,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      236,  236,  236,  236,  236,  237,  237,  237,  237,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  239,
        0,    0,    0,  239,    0,  239,  240,  240,  240,  241,
      241,  241,  241,  242,  242,  242,  242,  242,  242,  243,
      243,  243,  243,  244,  244,  244,  244,  244,  232,  232,

      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  232
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[59] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
/*Antwnopoulos Vasilis      | AEM 01270 | AM 2118204*/
/*Mpakalaros Kwnstantinos   | AEM 01279 | AM 2218213*/
/*Siatras  Odusseas         | AEM 00735 | AM 2116118*/
#line 6 "compiler.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <math.h>
	#include "tokens.h"

	 
     char str_buf[254];                    //String Buffer for saving string
     int error_counter=0;                  
	 
     void token_print(int token_id);
	 void iconstprint(int token_id, int base);		
	 void rconstprint(int token_id, int base);

	 int HexToInt(char* str);
	 int BinToInt(char* str);
		
	 float HexToFloat(char* str);		/*Had a problem during gcc with the linker of <math.h> and pow function */
	 float BinToFloat(char* str);		/*So i gave to use flag -lm with gcc to link it with library libm.a*/
	
     void yyerror(const char* err);

#line 722 "lex.yy.c"
/* Sub-Lexer | STRING = For Strings | SLCOMENT =  For single line comment */
 
/* Class Declaration */
/*For Finding IDs*/
/*			 (Hexademical)            					|(Binary)	     			|(Decimal)    (0)
/*ICONST    (0H[1-9][0-9A-F]*)	 				        |(0[B][1][01]*)			    |([1-9][0-9]*)|(0)*/
/*			 (Hexademical)					 			|(Binary)     		      	            |(Decimal)  (0)                     	               										       	 
/*RCONST	(((0H[A-F0-9]*)|0)\.([0-9A-F]*))			|((0B[1][0-1]*|0)\.[01]+)|(0B\.[01]+)	|\.[1-9]+E[+-]?[1-9]*|([1-9][0-9]*|0)?\.([1-9][0-9]*|0)|[1-9][0-9]*\.|([1-9]+E?[+-]?\.?[1-9]+[0-9]*)(E[+-]?[0-9]+)?|(0)*/
/*				ASCII 32-126 in hex | (\)(nftrbv)*/
#line 732 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define SLCOMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 60 "compiler.l"

#line 62 "compiler.l"
 /* Keywords */
#line 955 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 233 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 599 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "compiler.l"
{ token_print(T_FUNCTION); return T_FUNCTION; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "compiler.l"
{ token_print(T_SUBROUTINE); return T_SUBROUTINE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "compiler.l"
{ token_print(T_END); return T_END; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "compiler.l"
{ token_print(T_INTEGER); return T_INTEGER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "compiler.l"
{ token_print(T_REAL); return T_REAL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "compiler.l"
{ token_print(T_LOGICAL); return T_LOGICAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "compiler.l"
{ token_print(T_CHARACTER); return T_CHARACTER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "compiler.l"
{ token_print(T_RECORD); return T_RECORD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "compiler.l"
{ token_print(T_ENDREC); return T_ENDREC; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "compiler.l"
{ token_print(T_DATA); return T_DATA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "compiler.l"
{ token_print(T_CONTINUE); return T_CONTINUE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "compiler.l"
{ token_print(T_GOTO); return T_GOTO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "compiler.l"
{ token_print(T_CALL); return T_CALL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "compiler.l"
{ token_print(T_READ); return T_READ; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "compiler.l"
{ token_print(T_WRITE); return T_WRITE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "compiler.l"
{ token_print(T_IF); return T_IF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "compiler.l"
{ token_print(T_THEN); return T_THEN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "compiler.l"
{ token_print(T_ELSE); return T_ELSE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "compiler.l"
{ token_print(T_ENDIF); return T_ENDIF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "compiler.l"
{ token_print(T_DO); return T_DO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "compiler.l"
{ token_print(T_ENDDO); return T_ENDDO; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "compiler.l"
{ token_print(T_STOP); return T_STOP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "compiler.l"
{ token_print(T_RETURN); return T_RETURN; }
	YY_BREAK
/*ID*/
case 24:
YY_RULE_SETUP
#line 88 "compiler.l"
{ token_print(T_ID); return T_ID; }
	YY_BREAK
/*ICONST*/
case 25:
YY_RULE_SETUP
#line 91 "compiler.l"
{ iconstprint(T_ICONST, 16); return T_ICONST;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "compiler.l"
{ iconstprint(T_ICONST, 2); return T_ICONST;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "compiler.l"
{ iconstprint(T_ICONST, 10); return T_ICONST;}
	YY_BREAK
/*RCONST*/
case 28:
YY_RULE_SETUP
#line 96 "compiler.l"
{ rconstprint(T_RCONST, 16); return T_RCONST; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "compiler.l"
{ rconstprint(T_RCONST, 2 ); return T_RCONST; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "compiler.l"
{ rconstprint(T_RCONST, 10); return T_RCONST; }
	YY_BREAK
/*CCONST*/
case 31:
YY_RULE_SETUP
#line 101 "compiler.l"
{ token_print(T_CCONST); return T_CCONST; }
	YY_BREAK
/*LCONST*/
case 32:
YY_RULE_SETUP
#line 104 "compiler.l"
{ token_print(T_LCONST); return T_LCONST; }
	YY_BREAK
/* Operators */  
case 33:
YY_RULE_SETUP
#line 107 "compiler.l"
{ token_print(T_OROP); return T_OROP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "compiler.l"
{ token_print(T_ANDOP); return T_ANDOP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "compiler.l"
{ token_print(T_NOTOP); return T_NOTOP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "compiler.l"
{ token_print(T_RELOP); return T_RELOP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "compiler.l"
{ token_print(T_ADDOP); return T_ADDOP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "compiler.l"
{ token_print(T_MULOP); return T_MULOP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "compiler.l"
{ token_print(T_DIVOP); return T_DIVOP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "compiler.l"
{ token_print(T_POWEROP); return T_POWEROP; }
	YY_BREAK
/* For STRINGS */
case 41:
YY_RULE_SETUP
#line 117 "compiler.l"
{strcpy(str_buf, ""); BEGIN(STRING); }  /* Starting sub lexer for string */ /*Cleaning buffer*/ 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "compiler.l"
{ BEGIN(INITIAL);
                                if(strcmp(str_buf,"") ==0 ){    /* Checking if string is empty */
                                    yyerror("Found empty string"); 
                                   } else {
                                    printf("[LINE %d]Found String: '%s' (%d, %s) \n", yylineno, str_buf, T_STRING, TOKEN_NAME[T_STRING]); return T_STRING;}
                                }    
	YY_BREAK
/* Returning to lexer */
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 125 "compiler.l"
{ }                   /* New line for string */
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 126 "compiler.l"
{                       /* Catching  special characters */
                        if(strlen(yytext) == 2) {
								if(strcmp(yytext, "\\n") == 0) {
									strcat(str_buf, "\n");
								} else if (strcmp(yytext, "\\t") == 0 ) {
									strcat(str_buf, "\t");
								} else if (strcmp(yytext, "\\r") == 0) {
									strcat(str_buf, "\r");
								} else if (strcmp(yytext, "\\f") == 0) {
									strcat(str_buf, "\f");
								} else if (strcmp(yytext, "\\b") == 0) {
									strcat(str_buf, "\b");
								} else if (strcmp(yytext, "\\v") == 0) {
									strcat(str_buf, "\v");
								} else {
									strcat(str_buf, &yytext[1]);
								}
							}else {             /* Catching anything else */
								strcat(str_buf, yytext); 
							}
                        }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 147 "compiler.l"
{ yyerror("New line found without \\ \n"); }        /* New line without '\' ->  Error */
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 148 "compiler.l"
{ yyerror("End of string without closing it.\n"); } /* EOF in string ->  Error */
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "compiler.l"
{ yyerror("Unknown Character.\n"); }                /* Anything else -> Error */
	YY_BREAK
/* For SLCOMENT */
case 47:
YY_RULE_SETUP
#line 152 "compiler.l"
{ BEGIN(SLCOMMENT); printf("[LINE %d]Found Comment \n", yylineno); } 
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 153 "compiler.l"
{ BEGIN(INITIAL); } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 154 "compiler.l"
{  }                                        /* Ignore Commens */
	YY_BREAK
/* Other Lexical Tokens */
case 50:
YY_RULE_SETUP
#line 157 "compiler.l"
{ token_print(T_LPAREN); return T_LPAREN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 158 "compiler.l"
{ token_print(T_RPAREN); return T_RPAREN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "compiler.l"
{ token_print(T_COMMA); return T_COMMA; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 160 "compiler.l"
{ token_print(T_ASSIGN); return T_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 161 "compiler.l"
{ token_print(T_COLON); return T_COLON; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 162 "compiler.l"
{}						/* Ignore Spaces */
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 163 "compiler.l"
{} 				/* For New Line (Linux) |  For New Line (Windows) */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SLCOMMENT):
#line 164 "compiler.l"
{ token_print(T_EOF); return T_EOF; } //End of file
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 165 "compiler.l"
{ yyerror("Unrecognised character \n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "compiler.l"
ECHO;
	YY_BREAK
#line 1361 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 233 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 233 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 232);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 167 "compiler.l"


int main(int argc, char *argv[]){
	int token;        
	if(argc > 1){       

		yyin = fopen(argv[1], "r");
		if (yyin == NULL){
			perror ("Error opening file"); 
			return -1;
		}
	 }        

	do{		
		token = yylex(); 
	}while(token != T_EOF);
	fclose(yyin);
	yyterminate();
}


void token_print(int token_id) {
    printf("[LINE %d]Found token \'%s\' (%d, %s) \n", yylineno, yytext, token_id, TOKEN_NAME[token_id]);
}
 //Recognise iconst base convert to decimal and print
void iconstprint(int token_id, int base){		
        int number;
        if(base == 2) number = BinToInt(yytext);
        else if(base == 16) number = HexToInt(yytext);
        else number = atoi(yytext);
        printf("[LINE %d]Found number: %d (%s) | from base: %d | with token number: (%d, %s) \n", yylineno, number, yytext, base, token_id, TOKEN_NAME[token_id]);
    
}
 //Recognise rconst base convert to decimal and print
void rconstprint(int token_id, int base){
        float number;
        if(base == 2) number = BinToFloat(yytext);
        else if(base == 16) number = HexToFloat(yytext);
        else number = atof(yytext);
        printf("[LINE %d]Found float: %f (%s) | from base: %d | with token number: (%d, %s) \n", yylineno, number, yytext, base, token_id, TOKEN_NAME[token_id]);
    
}


//Function converting Hex to Int
int HexToInt(char *str){
    return (int) strtol(&str[2], NULL, 16);
}

//Function converting Bin to Int
int BinToInt(char *str){
    return (int) strtol(&str[2], NULL, 2);
}

//Function converting Hex to Float
float HexToFloat(char*str){
    float number = 0.0;
    int i,length_real;  
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,16);
    for(i=1;i<=length_real;i++){
        if(character[i] <= '9')
			number += (character[i] - '0') * (1/pow(16,i));
		else
			number += (character[i] + 10 - 'A') * (1/pow(16,i)); 
	}
    return number;
}

//Function converting Bin to Float
float BinToFloat(char* str){
    float number = 0.0;
    int i,length_real;
    char *character;
    character = strchr(str,'.');
    length_real = strlen(character)-1;
    number = (int)strtol(&str[2],&character,2);
    for(i=1;i<=length_real;i++){
        number += (character[i] - '0') * (1/pow(2,i));
    }
    return number;
}
//Function For Errors
void yyerror(const char* err){
    error_counter++;
    printf("[ERROR - LINE %d] %s\n", yylineno, err);

    if(error_counter == 5) {
        printf("MAXIMUM ERRORS FOUND\n");
        exit(EXIT_FAILURE);
    }
    yyless(1); /* Panic Method */
}
